users/urls.py
from django.urls import path

from . import views


app_name = "users"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
]

vkgroup/urls.py
from django.urls import path

from . import views


app_name = "groups"

urlpatterns = [
    path('create/', views.GroupCreateView.as_view(), name="create"),
    path('<slug:slug>/', views.GroupUserListView.as_view(), name="detail"),
    path('<slug:slug>/vote/', views.LikeView.as_view(), name="vote"),
]

vkvote/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import index_view

urlpatterns = [
    path('', index_view, name="home"),
    path('', include('users.urls', namespace="users")),
    path('', include('vkgroup.urls', namespace="groups")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Voter</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheets %}{% endblock stylesheets %}
</head>
<body>
    <div class="container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.5"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block js %}{% endblock js %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Ну привет, {{ request.user }}</h1>

    <ul>
    	{% for group in groups %}
    	<li>
			<a href="{% url 'groups:detail' group.slug %}">{{ group.title }}</a>
    	</li>
    	{% endfor %}
    </ul>
{% endblock content %}